title: Dot-to-dot
hero_image: images/banner.png
description:
version: 4
listed: false
copyedit: false
last_tested: "2018-12-06"
steps:
  - title: Introduction
  - title: Extracting points from an image
  - title: Plotting the points
  - title: Adding labels
  - title: Creating a function
  - title: "Challenge: improve your function"
    challenge: true
